# Generated by Django 6.1 on 2026-09-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='model',
            field=models.CharField(blank=True, help_text='Empty means DEFAULT_LLM_MODEL was used.', max_length=128),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='provider',
            field=models.CharField(blank=True, help_text='Empty means DEFAULT_LLM_PROVIDER was used.', max_length=64),
        ),
    ]
